// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: goflow.proto

package goflow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoFlow_PushTask_FullMethodName = "/goflow.GoFlow/PushTask"
)

// GoFlowClient is the client API for GoFlow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The GoFlow service definition.
type GoFlowClient interface {
	// Sends a task
	PushTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
}

type goFlowClient struct {
	cc grpc.ClientConnInterface
}

func NewGoFlowClient(cc grpc.ClientConnInterface) GoFlowClient {
	return &goFlowClient{cc}
}

func (c *goFlowClient) PushTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, GoFlow_PushTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoFlowServer is the server API for GoFlow service.
// All implementations must embed UnimplementedGoFlowServer
// for forward compatibility.
//
// The GoFlow service definition.
type GoFlowServer interface {
	// Sends a task
	PushTask(context.Context, *TaskRequest) (*TaskResponse, error)
	mustEmbedUnimplementedGoFlowServer()
}

// UnimplementedGoFlowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoFlowServer struct{}

func (UnimplementedGoFlowServer) PushTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushTask not implemented")
}
func (UnimplementedGoFlowServer) mustEmbedUnimplementedGoFlowServer() {}
func (UnimplementedGoFlowServer) testEmbeddedByValue()                {}

// UnsafeGoFlowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoFlowServer will
// result in compilation errors.
type UnsafeGoFlowServer interface {
	mustEmbedUnimplementedGoFlowServer()
}

func RegisterGoFlowServer(s grpc.ServiceRegistrar, srv GoFlowServer) {
	// If the following call pancis, it indicates UnimplementedGoFlowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoFlow_ServiceDesc, srv)
}

func _GoFlow_PushTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFlowServer).PushTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoFlow_PushTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFlowServer).PushTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoFlow_ServiceDesc is the grpc.ServiceDesc for GoFlow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoFlow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goflow.GoFlow",
	HandlerType: (*GoFlowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushTask",
			Handler:    _GoFlow_PushTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goflow.proto",
}
