goflow_server:
  image: "jamestait12/goflow-server:latest"
  replicas: 1
  address: "127.0.0.1"
  port: 50051
workerpool:
  image: "jamestait12/goflow-workerpool:latest"
  replicas: 5
  path_to_handlers: "/home/docker/handlers"
  plugin_builder_image: "jamestait12/goflow-plugin-builder:latest"
redis:
  image: "redis:latest"
  replicas: 1
kubernetes:
  namespace: "goflow"
  clusterUrl: "https://127.0.0.1:32771"
