linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    disabled-checks:
      - sloppyReassign
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 512
  govet:
    enable:
      # - fieldalignment
      - shadow
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: exported

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - goconst
    # - gocritic
    - gofmt
    - goimports
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
issues:
  exclude-dirs:
    - "example"
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - dupl
  exclude-use-default: false

run:
  issues-exit-code: 1
