FROM golang:1.23-bullseye AS builder
ENV CGO_ENABLED=0 GOOS=linux

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/goflow ./cmd/goflow
COPY pkg ./pkg

RUN go build -o goflow ./cmd/goflow

RUN go build -o goflow ./cmd/goflow

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/goflow .

EXPOSE 50051

CMD ["./goflow"]
