# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - stable
          - oldstable
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Lint
        uses: golangci/golangci-lint-action@v6.1.1
        with: 
          args: --out-format sarif:golangci-lint.sarif

      - name: Snyk
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload Lint Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: golangci-lint.sarif
      
      - name: Upload Snyk Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

      - name: Test
        run: go test -v -race ./...

      - name: Refresh Report Card
        uses: creekorful/goreportcard-action@v1.0

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - "1.20"
          - "1.21"
          - "1.22"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
      - run: go test -v -race ./...
